### ISSUE TITLE
nueva página para confirmar pre-inscripción e influir a inscripcion

### ISSUE THREAD

**Issue by sepu85** [daoeducation/site#15]
Al terminar el proceso de inscripcion en el typeform se dirige automáticamente al [checkout](https://dao.education/payments/zero_to_hero) para que el candidato pague (a partir de hoy 25 de enero, antes no hacía ninguna re-dirección).

Sin embargo, puede que el estudiante necesite más certeza de lo que está haciendo antes de pagar directamente sin haberle dado instrucciones más claras. En manera de crear más confianza en el proceso, propongo crear una página simple con un esquema del tipo:

![image](https://user-images.githubusercontent.com/22507864/105707917-f71fb600-5f13-11eb-92d6-c17d5b4ff0cf.png)

Link de inscripción: https://dao.education/payments/zero_to_hero
link de agendar una reunion: https://calendly.com/gus-daoe/15min?back=1&month=2021-01
link de mail: info@dao.education

nota: podría ser mejor que en vez de mail, un link a agregar a un whatsapp o telegram, personalmente no me siento tranquilo dando mi telefono personal como para que me escriban a whatsapp, y telegram podria ser una barrera de entradas para algunos, asi que mi primera propuesta es la del mail, pero estoy abierto a considerar nuevas ideas para abrir un chat directo conmigo o con alguien más del equipo. cc @santisiri

**Comment by bronxi47** [comment]
https://dao.education/signup_success está funcionando!
